#!/bin/bash
set -euxo pipefail

TAG="$TAG"
REGISTRY="$REGISTRY"
DIR="$(dirname "$0")"

MANAGER_IMG="$REGISTRY/manager"
CERTIFIER_IMG="$REGISTRY/certifier"
REPORTER_SERVER_IMG="$REGISTRY/example/reporter/server"
REPORTER_WORKER_IMG="$REGISTRY/example/reporter/worker"

cd "$DIR/.."
if [[ "${1:-}" == "push" ]]; then
  make docker-push-all MANAGER_IMG="$MANAGER_IMG" CERTIFIER_IMG="$CERTIFIER_IMG" REPORTER_SERVER_IMG="$REPORTER_SERVER_IMG" REPORTER_WORKER_IMG="$REPORTER_WORKER_IMG" TAG="$TAG"
else
  make docker-build-all MANAGER_IMG="$MANAGER_IMG" CERTIFIER_IMG="$CERTIFIER_IMG" REPORTER_SERVER_IMG="$REPORTER_SERVER_IMG" REPORTER_WORKER_IMG="$REPORTER_WORKER_IMG" TAG="$TAG"
fi
